spring:
  profiles:
    active: dev
  freemarker:
    request-context-attribute: request
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      topjet:
        manage:
          mapper: debug



message:
  push:
    title:
      idverifypass: "恭喜，您的实名认证已审核通过！"
      idverifyfail: "您提交的的实名认证信息未通过认证，请修改后重新提交!"
      idauthpass: "恭喜，您的身份认证已审核通过!"
      idauthfail: "您提交的的身份认证信息未通过认证，请修改后重新提交!"
      headauthpass: "恭喜您，您的头像修改已审核通过!"
      headauthfail: "对不起，您的头像修改审核失败，请按照示例重新上传头像。"
      carauthpass: "恭喜您，您提交的车辆信息已经审核通过！您现在可以去接货了！"
      carauthfail: "对不起，您提交的车辆信息认证失败，请重新提交。"
      goodspushmessage: "560匹配中心为您匹配新货源，从{0},{1}货物：{2}{3}，赶快去承接吧。打电话找货最高领取88.88元红包！"
      announcementmessage: "您有一条公告消息!"
      companypass: "企业信息已审核通过，您可前往网页端体验完善高效的560物流管理系统。"
      companyfail: "审核未通过，请重新提交企业信息。"
    button:
      text: "我知道了"


